import type { Blueprint, Decision, Guardrails, Map, MentalModel } from '../core/types';
import { describeConfidence } from '../core/knowledge';

export function renderMapMd(map: Map): string {
  const lines: string[] = [];
  lines.push('# Engineering Map');
  lines.push('');
  lines.push(`> Generated by EngineeringOS. Canonical source: \`.engineeringos/map.json\`. Do not edit this file by hand.`);
  lines.push('');
  lines.push(`**Model version:** ${map.modelVersion}  `);
  lines.push(`**Project:** ${map.project.name}`);
  lines.push('');

  if (map.project.purpose) {
    lines.push(`## System Purpose`);
    lines.push('');
    lines.push(map.project.purpose);
    lines.push('');
  }

  if (map.actors.length > 0) {
    lines.push('## Actors');
    lines.push('');
    for (const actor of map.actors) {
      lines.push(`### ${actor.name}`);
      lines.push('');
      lines.push(actor.description);
      lines.push('');
      if (actor.interactions.length > 0) {
        for (const i of actor.interactions) lines.push(`- ${i}`);
        lines.push('');
      }
    }
  }

  if (map.components.length > 0) {
    lines.push('## Components');
    lines.push('');
    for (const c of map.components) {
      lines.push(`### ${c.name} (\`${c.id}\`)`);
      lines.push('');
      if (c.purpose) lines.push(`${c.purpose}`);
      lines.push('');
      if (c.responsibilities.length > 0) {
        lines.push('**Responsibilities**');
        lines.push('');
        for (const r of c.responsibilities) lines.push(`- ${r}`);
        lines.push('');
      }
      if (c.dependencies.length > 0) {
        lines.push(`**Depends on:** ${c.dependencies.join(', ')}`);
        lines.push('');
      }
      if (c.dependents.length > 0) {
        lines.push(`**Used by:** ${c.dependents.join(', ')}`);
        lines.push('');
      }
      if (c.sourceLocations.length > 0) {
        lines.push('**Source locations**');
        lines.push('');
        for (const loc of c.sourceLocations) lines.push(`- \`${loc}\``);
        lines.push('');
      }
    }
  }

  if (map.relationships.length > 0) {
    lines.push('## Relationships');
    lines.push('');
    for (const r of map.relationships) {
      lines.push(`- \`${r.from}\` → \`${r.to}\` (${r.type})${r.description ? ` — ${r.description}` : ''}`);
    }
    lines.push('');
  }

  if (map.workflows.length > 0) {
    lines.push('## Workflows');
    lines.push('');
    for (const w of map.workflows) {
      lines.push(`### ${w.name}`);
      lines.push('');
      if (w.description) lines.push(`${w.description}`);
      lines.push('');
      lines.push('```text');
      w.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
      lines.push('```');
      lines.push('');
    }
  }

  if (map.dataFlows.length > 0) {
    lines.push('## Data Flows');
    lines.push('');
    for (const f of map.dataFlows) {
      lines.push(`### ${f.name}`);
      lines.push('');
      lines.push(f.description);
      lines.push('');
      for (const s of f.steps) {
        if (typeof s === 'string') lines.push(`- ${s}`);
        else lines.push(`- ${s.step}${s.from && s.to ? ` (\`${s.from}\` → \`${s.to}\`)` : ''}`);
      }
      lines.push('');
    }
  }

  if (map.externalSystems.length > 0) {
    lines.push('## External Systems');
    lines.push('');
    for (const e of map.externalSystems) {
      lines.push(`- **${e.name}** — ${e.purpose}`);
    }
    lines.push('');
  }

  if (map.dependencies.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    for (const d of map.dependencies) {
      lines.push(`- \`${d.name}\` (${d.type})${d.version ? ` ${d.version}` : ''}${d.critical ? ' ⚠ critical' : ''}`);
    }
    lines.push('');
  }

  if (map.requirements.length > 0) {
    lines.push('## Requirements');
    lines.push('');
    for (const r of map.requirements) {
      lines.push(`- **${r.id}** (${r.priority}, ${r.status}): ${r.text}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function renderMentalModelMd(model: MentalModel): string {
  const lines: string[] = [];
  lines.push('# Engineering Mental Model');
  lines.push('');
  lines.push(`> Generated by EngineeringOS. Canonical source: \`.engineeringos/mental-model.json\`. Do not edit this file by hand.`);
  lines.push('');
  lines.push(`**Model version:** ${model.modelVersion}`);
  lines.push('');
  lines.push('## System Understanding');
  lines.push('');
  if (model.systemUnderstanding.purpose) {
    lines.push(`**Purpose:** ${model.systemUnderstanding.purpose}`);
    lines.push('');
  }
  if (model.systemUnderstanding.businessObjective) {
    lines.push(`**Business objective:** ${model.systemUnderstanding.businessObjective}`);
    lines.push('');
  }
  if (model.systemUnderstanding.primaryUsers.length > 0) {
    lines.push(`**Primary users:** ${model.systemUnderstanding.primaryUsers.join(', ')}`);
    lines.push('');
  }
  if (model.systemUnderstanding.criticalCapabilities.length > 0) {
    lines.push('**Critical capabilities:**');
    lines.push('');
    for (const c of model.systemUnderstanding.criticalCapabilities) lines.push(`- ${c}`);
    lines.push('');
  }

  if (model.invariants.length > 0) {
    lines.push('## Invariants');
    lines.push('');
    for (const i of model.invariants) {
      lines.push(`- **${i.id}** (${i.severity}): ${i.statement}`);
      if (i.enforcement.length > 0) lines.push(`  - Enforcement: ${i.enforcement.join(', ')}`);
      if (i.verification.length > 0) lines.push(`  - Verification: ${i.verification.join(', ')}`);
    }
    lines.push('');
  }

  if (model.stateMachines.length > 0) {
    lines.push('## State Machines');
    lines.push('');
    for (const sm of model.stateMachines) {
      lines.push(`### ${sm.entity}`);
      lines.push('');
      lines.push(`States: ${sm.states.join(' → ')}`);
      lines.push('');
      if (sm.transitions.length > 0) {
        lines.push('```text');
        for (const t of sm.transitions) lines.push(`${t.from} --${t.trigger}--> ${t.to}`);
        lines.push('```');
        lines.push('');
      }
    }
  }

  if (model.causalRelationships.length > 0) {
    lines.push('## Causal Relationships');
    lines.push('');
    for (const c of model.causalRelationships) {
      lines.push(`### ${c.id}`);
      lines.push('');
      lines.push(`**Cause:** ${c.cause}`);
      lines.push('');
      lines.push(`**Effect:** ${c.effect}`);
      lines.push('');
      if (c.conditions.length > 0) {
        lines.push('**Conditions:**');
        lines.push('');
        for (const cond of c.conditions) lines.push(`- ${cond}`);
        lines.push('');
      }
    }
  }

  if (model.decisions.length > 0) {
    lines.push('## Decisions');
    lines.push('');
    for (const d of model.decisions) {
      lines.push(`### ${d.id} — ${d.title}`);
      lines.push('');
      lines.push(`**Status:** ${d.status}`);
      lines.push('');
      lines.push(`**Decision:** ${d.decision}`);
      lines.push('');
      lines.push(`**Reason:** ${d.reason}`);
      lines.push('');
    }
  }

  if (model.assumptions.length > 0) {
    lines.push('## Assumptions');
    lines.push('');
    for (const a of model.assumptions) {
      lines.push(`- **${a.id}** (${describeConfidence(a.confidence)}): ${a.statement}`);
    }
    lines.push('');
  }

  if (model.unknowns.length > 0) {
    lines.push('## Unknowns');
    lines.push('');
    for (const u of model.unknowns) {
      lines.push(`- **${u.id}** (impact: ${u.impact}): ${u.question}${u.blocks.length > 0 ? ` — blocks: ${u.blocks.join(', ')}` : ''}`);
    }
    lines.push('');
  }

  if (model.risks.length > 0) {
    lines.push('## Risks');
    lines.push('');
    for (const r of model.risks) {
      lines.push(`- **${r.name}** (${r.likelihood}/${r.impact}): ${r.description}${r.mitigation ? ` — Mitigation: ${r.mitigation}` : ''}`);
    }
    lines.push('');
  }

  if (model.failureModes.length > 0) {
    lines.push('## Failure Modes');
    lines.push('');
    for (const f of model.failureModes) {
      lines.push(`- **${f.name}** (${f.severity}): ${f.description} — Mitigation: ${f.mitigation}`);
    }
    lines.push('');
  }

  if (model.constraints.length > 0) {
    lines.push('## Constraints');
    lines.push('');
    for (const c of model.constraints) {
      lines.push(`- **${c.id}** (${c.scope}): ${c.statement}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function renderGuardrailsMd(guardrails: Guardrails): string {
  const lines: string[] = [];
  lines.push('# Engineering Guardrails');
  lines.push('');
  lines.push(`> Generated by EngineeringOS. Canonical source: \`.engineeringos/guardrails.json\`. Do not edit this file by hand.`);
  lines.push('');
  lines.push(`**Model version:** ${guardrails.modelVersion}`);
  lines.push('');
  lines.push('## Guardrails');
  lines.push('');
  for (const g of guardrails.guardrails) {
    lines.push(`### ${g.id} — ${g.name}`);
    lines.push('');
    lines.push(`**Severity:** ${g.severity.toUpperCase()}`);
    lines.push('');
    lines.push(`**Rule:** ${g.rule}`);
    lines.push('');
    if (g.scope.length > 0) {
      lines.push('**Scope:**');
      lines.push('');
      for (const s of g.scope) lines.push(`- \`${s}\``);
      lines.push('');
    }
    if (g.enforcement.length > 0) {
      lines.push(`**Enforcement:** ${g.enforcement.join(', ')}`);
      lines.push('');
    }
    if (g.reason) {
      lines.push(`**Reason:** ${g.reason}`);
      lines.push('');
    }
    if (g.verification.length > 0) {
      lines.push(`**Verification:** ${g.verification.join(', ')}`);
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function renderBlueprintMd(blueprint: Blueprint): string {
  const lines: string[] = [];
  lines.push('# Engineering Blueprint');
  lines.push('');
  lines.push(`> Generated by EngineeringOS. Canonical source: \`.engineeringos/blueprint.json\`. Do not edit this file by hand.`);
  lines.push('');
  lines.push(`**Version:** ${blueprint.version}  `);
  lines.push(`**Project:** ${blueprint.projectName}  `);
  lines.push(`**Architecture:** ${blueprint.architectureStyle}  `);
  lines.push(`**Security level:** ${blueprint.securityLevel}  `);
  if (blueprint.techStack.language || blueprint.techStack.framework || blueprint.techStack.database) {
    lines.push(`**Stack:** ${[blueprint.techStack.language, blueprint.techStack.runtime, blueprint.techStack.framework, blueprint.techStack.database].filter(Boolean).join(' · ')}`);
  }
  lines.push('');
  lines.push('> This document is the framework an AI coding agent MUST read and follow before, during, and after building the system. It complements `.engineeringos/map.json`, `.engineeringos/mental-model.json`, and `.engineeringos/guardrails.json`.');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 0. Mission');
  lines.push('');
  lines.push(blueprint.summary);
  lines.push('');

  if (blueprint.sourceSpec) {
    lines.push('---');
    lines.push('');
    lines.push('## User-Supplied Blueprint Requirements');
    lines.push('');
    lines.push('```text');
    lines.push(blueprint.sourceSpec);
    lines.push('```');
    lines.push('');
  }

  blueprint.sections.forEach((s, index) => {
    lines.push('---');
    lines.push('');
    lines.push(`## ${index + 1}. ${s.title}`);
    lines.push('');
    lines.push(s.purpose);
    lines.push('');
    for (const d of s.directives) {
      lines.push(`- ${d}`);
    }
    lines.push('');
  });

  lines.push('---');
  lines.push('');
  lines.push('_Every change to this system is verified against this blueprint, the map, the mental model, and the guardrails before it is accepted._');
  return lines.join('\n');
}

export function renderAdr(decision: Decision): string {
  const lines: string[] = [];
  lines.push(`# ${decision.title}`);
  lines.push('');
  lines.push(`**Status:** ${decision.status}`);
  lines.push('');
  lines.push('## Context');
  lines.push('');
  lines.push(decision.context);
  lines.push('');
  lines.push('## Decision');
  lines.push('');
  lines.push(decision.decision);
  lines.push('');
  lines.push('## Reason');
  lines.push('');
  lines.push(decision.reason);
  lines.push('');
  lines.push('## Alternatives');
  lines.push('');
  for (const a of decision.alternatives) lines.push(`- ${a}`);
  lines.push('');
  lines.push('## Consequences');
  lines.push('');
  for (const c of decision.consequences) lines.push(`- ${c}`);
  lines.push('');
  lines.push('## Affected Components');
  lines.push('');
  for (const c of decision.affectedComponents) lines.push(`- ${c}`);
  lines.push('');
  return lines.join('\n');
}
