export function generateGitHubActionsWorkflow(options?: {
  nodeVersion?: string;
  triggerOn?: string[];
  failOnBlock?: boolean;
  uploadSarif?: boolean;
}): string {
  const nodeVersion = options?.nodeVersion ?? '20';
  const triggers = options?.triggerOn ?? ['push', 'pull_request'];
  const failOnBlock = options?.failOnBlock ?? true;
  const uploadSarif = options?.uploadSarif ?? true;

  return `# EngineeringOS CI Workflow
# Generated by EngineeringOS v2.0.0
# Validates architecture, guardrails, health, and security on every push/PR.

name: EngineeringOS Validation

on:
  ${triggers.map(t => `${t}:`).join('\n  ')}

permissions:
  contents: read
  security-events: ${uploadSarif ? 'write' : 'read'}
  pull-requests: ${uploadSarif ? 'write' : 'read'}

jobs:
  engineeringos:
    name: EngineeringOS Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${nodeVersion}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: EngineeringOS — Analyze Repository
        run: npx tsx src/cli/index.ts analyze --format json > .engineeringos/ci/analyze.json
        continue-on-error: false

      - name: EngineeringOS — Validate Guardrails
        id: validate
        run: |
          npx tsx src/cli/index.ts validate --format json > .engineeringos/ci/validate.json
          npx tsx src/cli/index.ts validate --format sarif > .engineeringos/ci/validate.sarif
          EXIT_CODE=\$(npx tsx src/cli/index.ts validate --format text | tail -1; echo $?)
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

      - name: EngineeringOS — Health Report
        run: npx tsx src/cli/index.ts health --format json > .engineeringos/ci/health.json

      - name: EngineeringOS — Drift Check
        run: npx tsx src/cli/index.ts drift --format json > .engineeringos/ci/drift.json

      - name: EngineeringOS — Full Report
        run: npx tsx src/cli/index.ts report --format markdown > .engineeringos/ci/report.md

      ${uploadSarif ? `- name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: .engineeringos/ci/validate.sarif
          category: engineeringos` : ''}

      - name: EngineeringOS — PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('.engineeringos/ci/report.md', 'utf-8');
            const health = JSON.parse(fs.readFileSync('.engineeringos/ci/health.json', 'utf-8'));
            const validate = JSON.parse(fs.readFileSync('.engineeringos/ci/validate.json', 'utf-8'));
            const healthPct = Math.round(health.overall * 100);
            const violCount = validate.violations?.length ?? 0;
            const body = [
              '## EngineeringOS Validation Report',
              '',
              '**Health:** ' + healthPct + '% (' + health.grade + ')',
              '**Validation:** ' + validate.overall + ' (' + violCount + ' violations)',
              '',
              '<details>',
              '<summary>Full Report</summary>',
              '',
              report,
              '</details>'
            ].join('\\n');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Upload CI artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: engineeringos-results
          path: .engineeringos/ci/
          retention-days: 30

      ${failOnBlock ? `- name: Check for blocking violations
        if: steps.validate.outputs.exit_code == '2'
        run: |
          echo "EngineeringOS: BLOCKING violations detected. See validation report."
          exit 1` : ''}
`;
}

export function generateCIConfig(): Record<string, unknown> {
  return {
    engineeringos: {
      version: '2.0.0',
      checks: ['validate', 'health', 'drift'],
      failOnBlock: true,
      uploadSarif: true,
      prComment: true,
      artifacts: {
        retainDays: 30
      }
    }
  };
}
