import type { Verdict } from '../core/protocol';

export interface PRReportInput {
  commitSha: string | null;
  branch: string;
  baseBranch: string;
  changedFiles: string[];
  validation: {
    overall: Verdict;
    violations: { ruleId: string; severity: string; message: string; file?: string; line?: number }[];
  };
  health: {
    overall: number;
    grade: string;
    criticalOverrides: string[];
  };
  drift: {
    findings: { driftType: string; severity: string; title: string; evidence: string[] }[];
  };
  repository: {
    totalFiles: number;
    testFiles: number;
    languages: Record<string, number>;
  };
}

export function generatePRReportMarkdown(input: PRReportInput): string {
  const lines: string[] = [];

  lines.push('## EngineeringOS Validation Report', '');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Health | **${Math.round(input.health.overall * 100)}%** (${input.health.grade}) |`);
  lines.push(`| Validation | **${input.validation.overall}** |`);
  lines.push(`| Violations | **${input.validation.violations.length}** |`);
  lines.push(`| Drift findings | **${input.drift.findings.length}** |`);
  lines.push(`| Commit | \`${input.commitSha ?? 'N/A'}\` |`);
  lines.push(`| Changed files | ${input.changedFiles.length} |`);
  lines.push('');

  if (input.validation.overall === 'BLOCK') {
    lines.push('> **BLOCKED** — Guardrail violations must be resolved before merge.', '');
  } else if (input.validation.overall === 'REVIEW' || input.validation.overall === 'WARN') {
    lines.push('> **REVIEW** — Findings require attention before merge.', '');
  } else {
    lines.push('> **PASSED** — All checks green.', '');
  }

  if (input.validation.violations.length > 0) {
    lines.push('### Violations', '');
    for (const v of input.validation.violations.slice(0, 20)) {
      const icon = v.severity === 'BLOCKING' ? ':red_circle:' : v.severity === 'WARNING' ? ':yellow_circle:' : ':blue_circle:';
      lines.push(`- ${icon} **${v.ruleId}** ${v.message}${v.file ? ` at \`${v.file}:${v.line ?? ''}\`` : ''}`);
    }
    lines.push('');
  }

  if (input.health.criticalOverrides.length > 0) {
    lines.push('### Critical Overrides', '');
    for (const o of input.health.criticalOverrides) {
      lines.push(`- :red_circle: ${o}`);
    }
    lines.push('');
  }

  if (input.drift.findings.length > 0) {
    lines.push('### Drift Findings', '');
    for (const f of input.drift.findings.slice(0, 10)) {
      lines.push(`- **${f.driftType}** [${f.severity}] ${f.title}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by EngineeringOS v2.0.0 — [Documentation](https://github.com/engineeringos/engineeringos)*');

  return lines.join('\n');
}

export function generatePRReportJSON(input: PRReportInput): string {
  return JSON.stringify({
    engineeringos: '2.0.0',
    timestamp: new Date().toISOString(),
    commit: input.commitSha,
    branch: input.branch,
    base: input.baseBranch,
    verdict: input.validation.overall,
    health: { score: input.health.overall, grade: input.health.grade },
    violations: input.validation.violations.length,
    drift: input.drift.findings.length,
    changedFiles: input.changedFiles.length,
    repository: input.repository,
    details: {
      validation: input.validation,
      health: input.health,
      drift: input.drift
    }
  }, null, 2);
}

export function generateStatusCheckConclusion(verdict: Verdict): 'success' | 'failure' | 'neutral' {
  switch (verdict) {
    case 'PASS': return 'success';
    case 'BLOCK': return 'failure';
    case 'WARN':
    case 'REVIEW':
    case 'NOT_VALIDATED':
    case 'SKIP': return 'neutral';
  }
}
